deploytodotasker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView, RedirectView
from rest_framework_social_oauth2.views import RevokeTokenView
from allauth.account.views import ConfirmEmailView
from deploytodotaskerapp import views, apis,imageUpload


class MyRevokeTokenView(RevokeTokenView):
    def post(self, request, *args, **kwargs):
        print('request', request)
        print('request.META', request.META)
        print('request.data', request.data)
        print('request._request.GET', request._request.GET)
        print('request._request.POST', request._request.POST)

        return super().post(request, *args, **kwargs)


urlpatterns = [
   # url(r'^image/$', TemplateView.as_view(template_name="image.html"), name='image'),    
    url(r'^image/upload/$', imageUpload.upload_pic, name='upload_pic'),
  #  url(r'^$', TemplateView.as_view(template_name="base.html"), name='base'),
    url(r'^signup/$', TemplateView.as_view(template_name="signup.html"),name='signup'),
    url(r'^email-verification/$', TemplateView.as_view(template_name="email_verification.html"),name='email-verification'),
  #  url(r'^login/$', TemplateView.as_view(template_name="login.html"),name='login'),
   # url(r'^logout/$', TemplateView.as_view(template_name="logout.html"),name='logout'),
    url(r'^password-reset/$',TemplateView.as_view(template_name="password_reset.html"),name='password-reset'),
    url(r'^password-reset/confirm/$',TemplateView.as_view(template_name="password_reset_confirm.html"),name='password-reset-confirm'),

    #url(r'^user-details/$',TemplateView.as_view(template_name="user_details.html"),
     #   name='user-details'),
    #url(r'^password-change/$',TemplateView.as_view(template_name="password_change.html"),name='password-change'),

    #url(r'^accounts/profile/$', TemplateView.as_view(template_name='profile.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),

    # Registration
    url(r'^registration/login/$', auth_views.LoginView.as_view(),
        {'template_name': 'registration/login.html'},
        name = 'registration-login'),
    url(r'^registration/sign-out', auth_views.LogoutView.as_view(),
        {'next_page': '/'},
        name = 'registration-sign-out'),
    url(r'^registration/sign-up', views.registration_sign_up,
        name = 'registration-sign-up'),
    url(r'^registration/$', views.registration_home, name = 'registration-home'),

    url(r'^registration/account/$', views.registration_account, name = 'registration-account'),
    url(r'^registration/meal/$', views.registration_meal, name = 'registration-meal'),
    url(r'^registration/meal/add/$', views.registration_add_meal, name = 'registration-add-meal'),


    url(r'^registration/meal/edit/(?P<meal_id>\d+)/$', views.registration_edit_meal, name = 'registration-edit-meal'),
    url(r'^registration/order/$', views.registration_order, name = 'registration-order'),
    url(r'^registration/report/$', views.registration_report, name = 'registration-report'),

    url(r'^api/social/revoke-token/?$', MyRevokeTokenView.as_view(), name="revoke_token"),
    url(r'^api/registration/order/notification/(?P<last_request_time>.+)/$', apis.registration_order_notification),
    ##For authentication                     
    # Sign In/ Sign Up/ Sign Out
    url(r'^api/social/', include('rest_framework_social_oauth2.urls')),
    
    # /convert-token (sign in/ sign up)
    # /revoke-token (sign out)
    url(r'^rest-auth/registration/account-confirm-email/(?P<key>.+)/$', ConfirmEmailView.as_view(), name='account_confirm_email'),


    url(r'^rest-auth/',include('rest_auth.urls')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),

    # APIs for CUSTOMERS
    url(r'^api/customer/registrations/$', apis.customer_get_registrations),
    url(r'^api/customer/meals/(?P<registration_id>\d+)/$', apis.customer_get_meals),
    url(r'^api/customer/drinks/(?P<registration_id>\d+)/$', apis.customer_get_drinks),
    url(r'^api/customer/order/add/$', apis.customer_add_order),
    url(r'^api/paytm/response/', apis.response, name = 'responsetm'),
    url(r'^api/customer/order/latest/$', apis.customer_get_latest_order),
    url(r'^api/customer/driver/location/$', apis.customer_driver_location),

    # APIs for DRIVERS
    url(r'^api/driver/orders/ready/$', apis.driver_get_ready_orders),
    url(r'^api/driver/order/pick/$', apis.driver_pick_order),
    url(r'^api/driver/order/latest/$', apis.driver_get_latest_order),
    url(r'^api/driver/order/complete/$', apis.driver_complete_order),
    url(r'^api/driver/revenue/$', apis.driver_get_revenue),
    url(r'^api/driver/location/update/$', apis.driver_update_location),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deploytodotaskerapp/forms.py
from django import forms

from django.contrib.auth.models import User
from deploytodotaskerapp.models import Registration, Meal,ImageStore

class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "password", "first_name", "last_name", "email")

class UserFormForEdit(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = ("name", "phone", "address", "logo")

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        exclude = ("registration",)

class ImageUploadForm(forms.Form):
    """Image upload form."""
    token= forms.CharField(required=True)
    image = forms.ImageField()

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Django-rest-auth demo">
    <meta name="author" content="Tivix, Inc.">

    <title>django-rest-auth demo</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

<body role="document">

   


    <div class="container theme-showcase" role="main">
      {% block content %}{% endblock %}
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      var error_response = function(data){
        $('.api-response').html("API Response: " + data.status + ' ' + data.statusText + '<br/>Content: ' + data.responseText);
      }
      var susccess_response = function(data){
        $('.api-response').html("API Response: OK<br/>Content: " + JSON.stringify(data));
      }

      $().ready(function(){
        $('form.ajax-post button[type=submit]').click(function(){
          var form = $('form.ajax-post');
          $.post(form.attr('action'), form.serialize())
          .fail(function(data){error_response(data);})
          .done(function(data){susccess_response(data);});
          return false;
        });
      });
    </script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/email_confirm.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

templates/email_verification.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>E-mail verification</h3><hr/>
    {% include "fragments/email_verification_form.html" %}
  </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>django-rest-auth demo</h1>
    <p>Welcome in django-rest-auth demo project!</p>
  </div>
{% endblock %}

templates/image.html
<form action="{% url 'upload_pic' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
         <input id="image" type="text" class="" name="token">
        <input id="id_image" type="file" class="" name="image">
    </p>
    <input type="submit" value="Submit" />
</form>

templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Login</h3><hr/>
    {% include "fragments/login_form.html" %}
  </div>
{% endblock %}

templates/logout.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Logout</h3><hr/>
    {% include "fragments/logout_form.html" %}
  </div>
{% endblock %}

templates/password_change.html
{% extends "base.html" %}

{% block content %}

  <div class="row">
    <div class="form-group">
      <label for="token" class="col-sm-2 control-label">User Token</label>
      <div class="col-sm-4">
        <input name="token" type="text" class="form-control" id="token" placeholder="Token">
        <p class="help-block">Token received after login</p>
      </div>
    </div>
  </div>

  <div class="row">
    <h3>Update User Details</h3><hr/>
    {% include "fragments/password_change_form.html" %}
  </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
      $().ready(function(){
        $('form button[type=submit]').click(function(){
          var token = $('input[name=token]').val();
          var form = $('form');
          $.ajax({
            url: form.attr('action'),
            data: $('form').serialize(),
            type: "POST",
            beforeSend: function(xhr){xhr.setRequestHeader('Authorization', 'Token '+token);}
          }).fail(function(data){error_response(data);})
          .done(function(data){susccess_response(data);});
          return false;
        });

      });
    </script>
{% endblock %}

templates/password_reset.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Password reset</h3><hr/>
    {% include "fragments/password_reset_form.html" %}
  </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Password reset confirmation</h3><hr/>
    {% include "fragments/password_reset_confirm_form.html" %}
  </div>
{% endblock %}



{% block script %}
    <script type="text/javascript">
        var url_elements = window.location.pathname.split('/');
        if (url_elements.length == 6){
            var uid = url_elements[url_elements.length - 3];
            if (uid !== undefined){
                $('input[name=uid]').val(uid);
            }
            var token = url_elements[url_elements.length - 2];
            if (token !== undefined){
                $('input[name=token]').val(token);
            }
        }
    </script>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Signup</h3><hr/>
    {% include "fragments/signup_form.html" %}
  </div>
{% endblock %}

templates/user_details.html
{% extends "base.html" %}

{% block content %}

  <div class="row">
  <h3>Retrieve User Details</h3><hr/>
    <div class="form-group">
      <label for="token" class="col-sm-2 control-label">User Token</label>
      <div class="col-sm-4">
        <input name="token" type="text" class="form-control" id="token" placeholder="Token">
        <p class="help-block">Token received after login</p>
      </div>
      <button id="get-user-details" class="btn btn-primary">GET user details</button>
    </div>
  </div>

  <div class="row">
    <h3>Update User Details</h3><hr/>
    {% include "fragments/user_details_form.html" %}
  </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
      $().ready(function(){
        $('#get-user-details').click(function(){
          var token = $('input[name=token]').val();

          $.ajax({
            url: "{% url 'rest_user_details' %}",
            beforeSend: function(xhr){xhr.setRequestHeader('Authorization', 'Token '+token);},
            type: "GET",
            success: function(data) {
              $('input[name=username]').val(data.username);
              $('input[name=email]').val(data.email);
              $('input[name=first_name]').val(data.first_name);
              $('input[name=last_name]').val(data.last_name);
            }
          });
          return false;
        });

        $('form button[type=submit]').click(function(){
          var token = $('input[name=token]').val();
          var form = $('form');
          $.ajax({
            url: form.attr('action'),
            data: $('form').serialize(),
            type: "PUT",
            beforeSend: function(xhr){xhr.setRequestHeader('Authorization', 'Token '+token);}
          }).fail(function(data){error_response(data);})
          .done(function(data){susccess_response(data);});
          return false;
        });

      });
    </script>
{% endblock %}